import type { SchedulingInput } from "./types";

export const mockSchedulingInput: SchedulingInput = {
  sections: [
    {
      id: "SEC-101-A",
      course_id: "COURSE-101",
      department: "FIN",
      section_code: "A",
      instructor_id: "INST-ALPHA",
      expected_enrollment: 28,
      enrollment_cap: 30,
      allowed_meeting_patterns: ["MP-MW-60", "MP-TR-75"],
      room_requirements: ["projector"],
      crosslist_group_id: "CLG-1",
      tags: ["core_required"],
    },
    {
      id: "SEC-550-A",
      course_id: "COURSE-550",
      department: "ACCT",
      section_code: "A",
      instructor_id: "INST-GAMMA",
      expected_enrollment: 18,
      enrollment_cap: 25,
      allowed_meeting_patterns: ["MP-MW-60", "MP-TR-75"],
      room_requirements: ["case_room"],
      crosslist_group_id: "CLG-1",
      tags: ["upper_level_required"],
    },
    {
      id: "SEC-220-A",
      course_id: "COURSE-220",
      department: "OB",
      section_code: "A",
      instructor_id: "INST-BETA",
      expected_enrollment: 20,
      enrollment_cap: 24,
      allowed_meeting_patterns: ["MP-MW-60", "MP-TR-75"],
      room_requirements: [],
      crosslist_group_id: null,
      tags: ["elective"],
    },
    {
      id: "SEC-221-A",
      course_id: "COURSE-221",
      department: "OB",
      section_code: "A",
      instructor_id: "INST-BETA",
      expected_enrollment: 16,
      enrollment_cap: 20,
      allowed_meeting_patterns: ["MP-TR-75", "MP-F-90"],
      room_requirements: [],
      crosslist_group_id: null,
      tags: ["elective"],
    },
    {
      id: "SEC-330-A",
      course_id: "COURSE-330",
      department: "MKTG",
      section_code: "A",
      instructor_id: "INST-DELTA",
      expected_enrollment: 22,
      enrollment_cap: 30,
      allowed_meeting_patterns: ["MP-MW-60"],
      room_requirements: ["projector"],
      crosslist_group_id: null,
      tags: ["core_required"],
    },
  ],
  instructors: [
    {
      id: "INST-ALPHA",
      name: "Alice Johnson",
      rank_type: "Tenured",
      unavailable_times: [],
      preferences: {
        preferred_days: ["Tue", "Thu"],
        preferred_patterns: ["MP-TR-75"],
        max_teaching_days: 3,
      },
    },
    {
      id: "INST-BETA",
      name: "Brian Lee",
      rank_type: "Adjunct",
      unavailable_times: [],
      preferences: {
        preferred_days: ["Tue", "Thu"],
        preferred_patterns: ["MP-TR-75", "MP-F-90"],
        max_teaching_days: 2,
      },
    },
    {
      id: "INST-GAMMA",
      name: "Grace Kim",
      rank_type: "TT",
      unavailable_times: [],
      preferences: {
        preferred_days: ["Mon", "Wed"],
        preferred_patterns: ["MP-MW-60"],
      },
    },
    {
      id: "INST-DELTA",
      name: "Daniel Park",
      rank_type: "NTT",
      unavailable_times: [],
      preferences: {
        preferred_days: ["Mon", "Wed"],
        preferred_patterns: ["MP-MW-60"],
      },
    },
  ],
  rooms: [
    {
      id: "ROOM-A",
      building: "Peters",
      room_number: "A-101",
      capacity: 60,
      features: ["projector", "case_room"],
    },
    {
      id: "ROOM-B",
      building: "Smith",
      room_number: "B-204",
      capacity: 40,
      features: ["projector"],
    },
    {
      id: "ROOM-C",
      building: "Smith",
      room_number: "C-110",
      capacity: 25,
      features: [],
    },
  ],
  timeslots: [
    { id: "TS-M-0900", day: "Mon", start_time: "09:00", end_time: "10:00", slot_type: "standard" },
    { id: "TS-M-1030", day: "Mon", start_time: "10:30", end_time: "11:30", slot_type: "standard" },
    { id: "TS-W-0900", day: "Wed", start_time: "09:00", end_time: "10:00", slot_type: "standard" },
    { id: "TS-W-1030", day: "Wed", start_time: "10:30", end_time: "11:30", slot_type: "standard" },
    { id: "TS-T-0900", day: "Tue", start_time: "09:00", end_time: "10:15", slot_type: "standard" },
    { id: "TS-T-1030", day: "Tue", start_time: "10:30", end_time: "11:45", slot_type: "standard" },
    { id: "TS-TH-0900", day: "Thu", start_time: "09:00", end_time: "10:15", slot_type: "standard" },
    { id: "TS-TH-1030", day: "Thu", start_time: "10:30", end_time: "11:45", slot_type: "standard" },
    { id: "TS-F-0900", day: "Fri", start_time: "09:00", end_time: "10:30", slot_type: "standard" },
  ],
  meeting_patterns: [
    {
      id: "MP-MW-60",
      slots_required: 2,
      allowed_days: ["Mon", "Wed"],
      compatible_timeslot_sets: [
        ["TS-M-0900", "TS-W-0900"],
        ["TS-M-1030", "TS-W-1030"],
      ],
    },
    {
      id: "MP-TR-75",
      slots_required: 2,
      allowed_days: ["Tue", "Thu"],
      compatible_timeslot_sets: [
        ["TS-T-0900", "TS-TH-0900"],
        ["TS-T-1030", "TS-TH-1030"],
      ],
    },
    {
      id: "MP-F-90",
      slots_required: 1,
      allowed_days: ["Fri"],
      compatible_timeslot_sets: [["TS-F-0900"]],
    },
  ],
  crosslist_groups: [
    {
      id: "CLG-1",
      member_section_ids: ["SEC-101-A", "SEC-550-A"],
      require_same_room: true,
    },
  ],
  no_overlap_groups: [
    {
      id: "NOG-1",
      member_section_ids: ["SEC-220-A", "SEC-330-A"],
      reason: "core_required_conflict",
    },
  ],
  blocked_times: [
    {
      scope: "global",
      timeslot_ids: ["TS-T-0900"],
      reason: "university_event",
    },
  ],
  locked_assignments: [
    {
      section_id: "SEC-330-A",
      fixed_timeslot_set: ["TS-M-0900", "TS-W-0900"],
      fixed_room: "ROOM-B",
    },
  ],
  soft_locks: [
    {
      section_id: "SEC-101-A",
      preferred_timeslot_set: ["TS-T-1030", "TS-TH-1030"],
      weight: 80,
    },
    {
      section_id: "SEC-220-A",
      preferred_room: "ROOM-A",
      weight: 50,
    },
  ],
};
